import Link from "next/link";
import { ArrowRight, BarChart3, Check, FileText, Menu, Sparkles, Target } from "lucide-react";

const tools = [
  ["/builder", FileText, "Resume Builder", "Create a polished student resume with a live preview."],
  ["/ai-tools", Sparkles, "AI Career Tools", "Improve summaries and bullets without making up experience."],
  ["/ats", BarChart3, "ATS Readiness", "Check structure, keywords and common readability issues."],
  ["/templates", Target, "Templates", "Pick a clean layout for internships, placements or graduate roles."],
];

export default function Home() {
  return (
    <main className="min-h-screen bg-[#071014] text-white">
      <header className="sticky top-0 z-50 border-b border-white/10 bg-[#071014]/90 px-4 py-4 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between"><Link href="/" className="text-xl font-bold">Resume<span className="text-[#6ee7b7]">Forge</span><span className="ml-1 text-xs text-white/35">AI</span></Link><nav className="hidden items-center gap-6 text-sm text-white/55 md:flex"><Link href="/ai-tools" className="hover:text-white">AI Tools</Link><Link href="/templates" className="hover:text-white">Templates</Link><Link href="/ats" className="hover:text-white">ATS Check</Link><Link href="/how-it-works" className="hover:text-white">How it works</Link><Link href="/login" className="rounded-xl border border-white/10 px-4 py-2 hover:bg-white/5">Sign in</Link><Link href="/signup" className="rounded-xl bg-[#6ee7b7] px-4 py-2 font-bold text-[#071014]">Get Started</Link></nav><details className="relative md:hidden"><summary className="flex h-10 w-10 cursor-pointer list-none items-center justify-center rounded-xl border border-white/10"><Menu size={18}/></summary><div className="absolute right-0 top-12 w-56 rounded-2xl border border-white/10 bg-[#0b171c] p-2 shadow-xl"><Link className="block rounded-xl p-3" href="/ai-tools">AI Tools</Link><Link className="block rounded-xl p-3" href="/templates">Templates</Link><Link className="block rounded-xl p-3" href="/ats">ATS Check</Link><Link className="block rounded-xl p-3" href="/how-it-works">How it works</Link><Link className="mt-2 block rounded-xl bg-[#6ee7b7] p-3 text-center font-bold text-[#071014]" href="/builder">Build my resume</Link></div></details></div></header>
      <section className="relative overflow-hidden"><div className="pointer-events-none absolute left-1/2 top-[-200px] h-[500px] w-[700px] -translate-x-1/2 rounded-full bg-[#6ee7b7]/10 blur-[120px]"/><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 py-20 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:py-28"><div><div className="inline-flex items-center gap-2 rounded-full border border-[#6ee7b7]/20 bg-[#6ee7b7]/[0.06] px-4 py-2 text-xs font-bold tracking-wider text-[#6ee7b7]"><span className="h-1.5 w-1.5 rounded-full bg-[#6ee7b7]"/> BUILT FOR STUDENTS</div><h1 className="mt-7 text-5xl font-semibold tracking-[-0.05em] sm:text-6xl lg:text-7xl">Your projects deserve a <span className="text-[#6ee7b7]">better resume.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-white/45 sm:text-lg">Turn coursework, projects, skills and early experience into a professional resume. Build it, improve it, check it and prepare it for real applications.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/builder" className="flex items-center justify-center gap-2 rounded-xl bg-[#6ee7b7] px-6 py-3.5 font-bold text-[#071014] hover:bg-[#a3e635]">Create my resume <ArrowRight size={17}/></Link><Link href="/templates" className="flex items-center justify-center rounded-xl border border-white/10 px-6 py-3.5 font-semibold text-white/75 hover:bg-white/5">Explore templates</Link></div><div className="mt-7 flex flex-wrap gap-5 text-xs text-white/35"><span><Check className="mr-1 inline text-[#6ee7b7]" size={14}/> No design skills needed</span><span><Check className="mr-1 inline text-[#6ee7b7]" size={14}/> Live preview</span><span><Check className="mr-1 inline text-[#6ee7b7]" size={14}/> ATS-aware</span></div></div><ResumeMockup/></div></section>
      <section className="mx-auto max-w-7xl px-4 py-12 sm:px-8"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{tools.map(([href,Icon,title,text])=>{const I=Icon as typeof FileText;return <Link key={title as string} href={href as string} className="group rounded-3xl border border-white/10 bg-[#0b171c] p-6 transition hover:-translate-y-1 hover:border-[#6ee7b7]/30"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#6ee7b7]/10 text-[#6ee7b7]"><I size={20}/></div><h2 className="mt-5 font-semibold">{title as string}</h2><p className="mt-2 text-sm leading-6 text-white/40">{text as string}</p><span className="mt-5 inline-flex items-center gap-1 text-xs font-bold text-[#6ee7b7]">Open tool <ArrowRight size={13}/></span></Link>})}</div></section>
      <section className="mx-auto max-w-7xl px-4 py-16 sm:px-8"><div className="rounded-[2rem] border border-white/10 bg-[#0b171c] p-7 sm:p-10"><p className="text-xs font-bold tracking-[0.2em] text-[#6ee7b7]">THE STUDENT WORKFLOW</p><h2 className="mt-3 text-3xl font-semibold sm:text-4xl">Everything you need before you hit Apply.</h2><div className="mt-9 grid gap-3 md:grid-cols-4">{["Add your education, projects and skills","Choose a professional template","Improve content and check ATS readiness","Export a clean resume for applications"].map((x,i)=><div key={x} className="rounded-2xl border border-white/10 bg-white/[0.02] p-5"><span className="text-xs font-bold text-[#6ee7b7]">0{i+1}</span><p className="mt-4 text-sm leading-6 text-white/60">{x}</p></div>)}</div><Link href="/how-it-works" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-[#6ee7b7]">See the full workflow <ArrowRight size={15}/></Link></div></section>
      <footer className="border-t border-white/10 px-4 py-10 text-center text-xs text-white/30">© {new Date().getFullYear()} ResumeForge AI · Built to help students present real skills clearly.</footer>
    </main>
  );
}
function ResumeMockup(){return <div className="mx-auto w-full max-w-md rounded-[2rem] border border-white/10 bg-white/[0.04] p-4 shadow-2xl"><div className="rounded-2xl bg-white p-6 text-slate-900"><div className="border-b border-slate-200 pb-5"><div className="text-2xl font-bold">YOUR NAME</div><div className="mt-1 text-xs text-slate-500">Student · Aspiring Developer</div></div>{["PROFILE","EDUCATION","PROJECTS","SKILLS"].map(s=><div className="mt-6" key={s}><div className="text-[10px] font-bold tracking-widest text-slate-500">{s}</div><div className="mt-2 h-2 w-full rounded bg-slate-100"/><div className="mt-2 h-2 w-11/12 rounded bg-slate-100"/><div className="mt-2 h-2 w-4/5 rounded bg-slate-100"/></div>)}</div></div>}
